backend:
  # name: test-repo
  name: github
  repo: ygout/portfolio-gatsby # Path to your GitHub repository
media_folder: 'static/images'
public_folder: '/images'
collections:
  - name: 'projects'
    label: 'Projects'
    folder: 'src/pages/projects'
    create: true
    slug: '{{slug}}'
    fields:
      - { name: 'title', label: 'Title', required: true }
      - { name: 'thumbnail', label: 'Thumbnail', widget: 'image' }
      - {
          name: 'gallery',
          label: 'Gallery',
          widget: 'list',
          field:
            {
              label: Image,
              name: image,
              widget: image,
              config: { multiple: true },
            },
          required: false,
          default: [null],
        }
      - {
          name: 'description',
          label: 'Description',
          widget: 'markdown',
          required: false,
          default: '',
        }
      - {
          name: 'tools',
          label: 'Tools',
          widget: 'string',
          required: false,
          default: '',
        }
      - {
          name: 'langages',
          label: 'Langages',
          widget: 'markdown',
          required: false,
          default: '',
        }
      - {
          name: 'results',
          label: 'Results',
          widget: 'markdown',
          required: false,
          default: '',
        }
      - {
          name: 'src_file',
          label: 'Source file',
          widget: 'list',
          field: { label: 'SrcFile', name: srcFile, widget: object, fields: [{ label: Url, name: url, widget: 'string' },{ label: Label, name: label, widget: 'string' }]},
          required: false,
        }
      - {
          name: 'category',
          label: 'Category',
          widget: 'select',
          default: 'WEB',
          options:
            [
              { label: 'Web', value: 'WEB' },
              { label: 'Logiciel', value: 'SOFTWARE' },
              { label: 'Mobile', value: 'MOBILE' },
            ],
          required: true,
        }
  # - name: 'moncv'
  #   label: 'Monmoncv'
  #   folder: 'src'
  #   create: true
  #   extension: 'json'
  #   fields:
  #     - {
  #         name: 'skills',
  #         label: 'Skills',
  #         widget: 'list',
  #         fields:
  #           [
  #             { label: 'Test', name: 'test', widget: 'string' },
  #             { label: 'Percent', name: 'percent', widget: 'number' },
  #           ],
  #       }
