backend:
  # name: test-repo
  name: github
  repo: ygout/portfolio-gatsby # Path to your GitHub repository
media_folder: 'static/images'
public_folder: '/images'
editor:
  preview: false
collections:
  - name: 'projects'
    label: 'Projects'
    folder: 'src/pages/projects'
    create: true
    slug: "{{slug}}"
    fields:
      - { name: 'title', label: 'Title', required: true }
      - {
          name: 'thumbnail',
          label: 'Thumbnail',
          widget: 'image',
          required: false,
        }
      - {
          name: 'gallery',
          label: 'Gallery',
          widget: 'list',
          field: { label: Image, name: image, widget: image },
          required: false,
        }
      - {
          name: 'description',
          label: 'Description',
          widget: 'markdown',
          required: false,
        }
      - { name: 'outils', label: 'Tools', widget: 'markdown', required: false }
      - {
          name: 'langages',
          label: 'Langages',
          widget: 'markdown',
          required: false,
        }
      - {
          name: 'results',
          label: 'Results',
          widget: 'markdown',
          required: false,
        }
      - {
          name: 'category',
          label: 'Category',
          widget: 'select',
          default: 'WEB',
          options:
            [
              { label: 'Web', value: 'WEB' },
              { label: 'Logiciel', value: 'SOFTWARE' },
              { label: 'Mobile', value: 'MOBILE' },
            ],
          required: true,
        }
  - name: 'skills'
    label: 'Skills'
    folder: 'src/data/skills'
    create: true
    fields: 
      - {name: 'name', label: 'Name', widget: 'string', required: true}
      - {name: 'percent', label: 'Percent', widget: 'number', required: true}
  - name: 'educations'
    label: 'Educations'
    folder: 'src/data/educations'
    create: true
    fields: 
      - {name: 'title', label: 'Title', widget: 'string', required: true}
      - {name: 'period', label: 'Period', widget: 'string', required: true}
      - {name: 'place', label: 'Place', widget: 'string', required: true}
  - name: 'experiences'
    label: 'Experiences'
    folder: 'src/data/experiences'
    create: true
    fields: 
      - {name: 'position', label: 'Position', widget: 'string', required: true}
      - {name: 'place', label: 'Place', widget: 'string', required: true}
      - {name: 'description', label: 'Description', widget: 'markdown', required: true}
