backend:
  # name: test-repo
  name: github
  repo: ygout/portfolio-gatsby # Path to your GitHub repository
media_folder: 'static/images'
public_folder: '/images'
media_library:
  name: cloudinary
  config:
    cloud_name: ygout
    api_key: '919667545191316'
collections:
  - name: 'projects'
    label: 'Projects'
    folder: 'src/pages/projects'
    create: true
    slug: '{{slug}}'
    fields:
      - { name: 'title', label: 'Title', required: true }
      - { name: 'thumbnail', label: 'Thumbnail', widget: 'image' }
      - {
          name: 'gallery',
          label: 'Gallery',
          widget: 'list',
          field:
            {
              label: Image,
              name: image,
              widget: image,
              media_library: { multiple: true },
            },
          required: false,
          default: [null],
        }
      - {
          name: 'description',
          label: 'Description',
          widget: 'markdown',
          required: false,
          default: '',
        }
      - {
          name: 'tools',
          label: 'Tools',
          widget: 'string',
          required: false,
          default: '',
        }
      - {
          name: 'langages',
          label: 'Langages',
          widget: 'markdown',
          required: false,
          default: '',
        }
      - {
          name: 'results',
          label: 'Results',
          widget: 'markdown',
          required: false,
          default: '',
        }
      - {
          name: 'src_file',
          label: 'Source file',
          widget: 'list',
          fields:
            [
              {
                label: 'SrcFile',
                name: srcFile,
                widget: object,
                fields:
                  [
                    { label: Url, name: url, widget: 'string', default: '' },
                    {
                      label: Label,
                      name: label,
                      widget: 'string',
                      default: '',
                    },
                  ],
              },
            ],
          required: false,
        }
      - {
          name: 'category',
          label: 'Category',
          widget: 'select',
          default: 'WEB',
          options:
            [
              { label: 'Web', value: 'WEB' },
              { label: 'Logiciel', value: 'SOFTWARE' },
              { label: 'Mobile', value: 'MOBILE' },
            ],
          required: true,
        }
        
  - label: 'Categories'
    name: 'categories'
    folder: 'src/data/categories'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Value', name: 'value', widget: 'string' }

  - label: 'Experiences'
    name: 'experiences'
    folder: 'src/data/experiences'
    create: true
    fields:
      - { label: 'Start date', name: 'startDate', widget: 'string' }
      - { label: 'End date', name: 'endDate', widget: 'string' }
      - { label: 'Job', name: 'job', widget: 'string' }
      - { label: 'Company', name: 'company', widget: 'string' }
      - { label: 'Place', name: 'place', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - {
          name: 'category',
          label: 'Category',
          widget: 'select',
          default: 'WEB',
          options:
            [
              { label: 'Ecole', value: 'SCHOOL' },
              { label: 'Professionnel', value: 'PRO' },
              { label: 'Personnel', value: 'PERSO' },
            ],
        }
  - label: 'Educations'
    name: 'educations'
    folder: 'src/data/educations'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Speciality', name: 'speciality', widget: 'string' }
      - { label: 'Start date', name: 'startDate', widget: 'string' }
      - { label: 'End date', name: 'endDate', widget: 'string' }
      - { label: 'School', name: 'school', widget: 'string' }
      - { label: 'Place', name: 'place', widget: 'string' }

  - label: 'Skills'
    name: 'skills'
    folder: 'src/data/skills'
    create: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Value', name: 'value', widget: 'number', max: 100}
      - {
          name: 'category',
          label: 'Category',
          widget: 'select',
          default: 'LANGUAGE',
          options:
            [
              { label: 'Langage', value: 'LANGUAGE' },
              { label: 'Framework', value: 'FRAMEWORK' },
              { label: 'Outils', value: 'TOOLS' },
            ],
        }